import {
  CircleDot,
  Globe,
  FileText,
  BarChart3,
  LayoutDashboard,
  FormInput,
  Settings,
  Users,
  Calendar,
  ClipboardList,
  Link as LinkIcon,
  Heart,
  Building2,
  Home,
  Mail,
  MessageSquare,
  Phone,
  Image,
  BookOpen,
  GraduationCap,
  Shield,
  Lock,
  Key,
  Bell,
  Star,
  Flag,
  Tag,
  Folder,
  Database,
  Server,
  Wifi,
  Cloud,
  Briefcase,
  Stethoscope,
  Activity,
  Pill,
  HeartHandshake,
  ClipboardCheck,
  CalendarCheck,
  FileCheck,
  Search,
  Lightbulb,
  type LucideIcon,
} from 'lucide-react'
import { APP_ICON_OPTIONS } from '@/types/app'

const ICON_MAP: Record<string, LucideIcon> = {
  'circle-dot': CircleDot,
  globe: Globe,
  'file-text': FileText,
  'bar-chart-3': BarChart3,
  'layout-dashboard': LayoutDashboard,
  'form-input': FormInput,
  settings: Settings,
  users: Users,
  calendar: Calendar,
  'clipboard-list': ClipboardList,
  link: LinkIcon,
  heart: Heart,
  'building-2': Building2,
  home: Home,
  mail: Mail,
  'message-square': MessageSquare,
  phone: Phone,
  image: Image,
  'book-open': BookOpen,
  'graduation-cap': GraduationCap,
  shield: Shield,
  lock: Lock,
  key: Key,
  bell: Bell,
  star: Star,
  flag: Flag,
  tag: Tag,
  folder: Folder,
  database: Database,
  server: Server,
  wifi: Wifi,
  cloud: Cloud,
  briefcase: Briefcase,
  stethoscope: Stethoscope,
  activity: Activity,
  pill: Pill,
  'heart-handshake': HeartHandshake,
  'hand-heart': HeartHandshake, // alias (was HandHeart, niet in lucide 0.294)
  'clipboard-check': ClipboardCheck,
  'calendar-check': CalendarCheck,
  'file-check': FileCheck,
  search: Search,
  lightbulb: Lightbulb,
}

export { APP_ICON_OPTIONS }

export function getAppIcon(iconKey: string | null): LucideIcon {
  if (iconKey && ICON_MAP[iconKey]) return ICON_MAP[iconKey]
  return CircleDot
}

export function getAppIconOrNull(iconKey: string | null): LucideIcon | null {
  if (iconKey && ICON_MAP[iconKey]) return ICON_MAP[iconKey]
  return null
}
