-- Extra app-icoon opties voor de grotere visuele icoonkiezer (Publicatie-tab).
INSERT INTO public.reference_options (category, value, label, sort_order, prioriteit_bonus)
VALUES
  ('app_icon', 'heart', 'Hart', 11, 0),
  ('app_icon', 'building-2', 'Gebouw', 12, 0),
  ('app_icon', 'home', 'Home', 13, 0),
  ('app_icon', 'mail', 'Mail', 14, 0),
  ('app_icon', 'message-square', 'Bericht', 15, 0),
  ('app_icon', 'phone', 'Telefoon', 16, 0),
  ('app_icon', 'image', 'Afbeelding', 17, 0),
  ('app_icon', 'book-open', 'Boek', 18, 0),
  ('app_icon', 'graduation-cap', 'Opleiding', 19, 0),
  ('app_icon', 'shield', 'Schild', 20, 0),
  ('app_icon', 'lock', 'Slot', 21, 0),
  ('app_icon', 'key', 'Sleutel', 22, 0),
  ('app_icon', 'bell', 'Bel', 23, 0),
  ('app_icon', 'star', 'Ster', 24, 0),
  ('app_icon', 'flag', 'Vlag', 25, 0),
  ('app_icon', 'tag', 'Tag', 26, 0),
  ('app_icon', 'folder', 'Map', 27, 0),
  ('app_icon', 'database', 'Database', 28, 0),
  ('app_icon', 'server', 'Server', 29, 0),
  ('app_icon', 'wifi', 'Wifi', 30, 0),
  ('app_icon', 'cloud', 'Cloud', 31, 0),
  ('app_icon', 'briefcase', 'Koffer', 32, 0),
  ('app_icon', 'stethoscope', 'Stethoscoop', 33, 0),
  ('app_icon', 'activity', 'Activiteit', 34, 0),
  ('app_icon', 'pill', 'Medicijn', 35, 0),
  ('app_icon', 'heart-handshake', 'Zorg', 36, 0),
  ('app_icon', 'clipboard-check', 'Checklist', 37, 0),
  ('app_icon', 'calendar-check', 'Afspraak', 38, 0),
  ('app_icon', 'file-check', 'Document OK', 39, 0),
  ('app_icon', 'search', 'Zoeken', 40, 0),
  ('app_icon', 'lightbulb', 'Idee', 41, 0)
ON CONFLICT (category, value) DO NOTHING;
